# Generated by Django 2.2.1 on 2019-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='total_amt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
