# Generated by Django 2.2.1 on 2019-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_foodorder_total_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='id',
        ),
        migrations.AddField(
            model_name='foodorder',
            name='foid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
