# Generated by Django 2.2.1 on 2019-06-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_pastorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastOrders',
        ),
    ]
