# Generated by Django 2.2.1 on 2019-06-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_pastorders_foodorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PastOrders',
        ),
    ]
