# Generated by Django 2.2.1 on 2019-06-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_pastorders_poid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastorders',
            name='food2',
        ),
        migrations.RemoveField(
            model_name='pastorders',
            name='poid',
        ),
        migrations.AddField(
            model_name='pastorders',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pastorders',
            name='customer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastorders',
            name='foodlist',
            field=models.TextField(null=True),
        ),
    ]
