# Generated by Django 2.2.1 on 2019-06-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190619_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='Main Course', max_length=50),
        ),
    ]
